version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "16:00"
      day: "sunday"
      timezone: "Asia/Kolkata"
    groups:
      prod-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "auto-merge"
    ignore:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "16:00"
      day: "sunday"
      timezone: "Asia/Kolkata"
    groups:
      prod-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-type: "development"